[0m15:27:50.346115 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbe85c69ab0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbe85fae7a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbe85fae740>]}


============================== 15:27:50.348439 | 43e8a008-0de6-479a-944d-fc10234b5447 ==============================
[0m15:27:50.348439 [info ] [MainThread]: Running with dbt=1.8.1
[0m15:27:50.348780 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': './transform/profiles', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run-operation load_vocabularies --profiles-dir=./transform/profiles --args {"path":"/home/judith/OMOP Vocabularies/21-Feb-24/"}', 'send_anonymous_usage_stats': 'True'}
[0m15:27:50.349105 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/judith/Documents/Judith/Master/TFM/TFM/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:27:50.349606 [debug] [MainThread]: Resource report: {"command_name": "run-operation", "command_wall_clock_time": 0.039145052, "process_user_time": 0.822002, "process_kernel_time": 0.015961, "process_mem_max_rss": "85248", "process_in_blocks": "208", "process_out_blocks": "8", "command_success": false}
[0m15:27:50.349976 [debug] [MainThread]: Command `dbt run-operation` failed at 15:27:50.349911 after 0.04 seconds
[0m15:27:50.350217 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbe85c69ab0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbe85fae860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbe85faea10>]}
[0m15:27:50.350468 [debug] [MainThread]: Flushing usage events
[0m15:27:51.351427 [debug] [MainThread]: An error was encountered while trying to flush usage events
